spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: springcloud-config-dev
---
spring:
  profiles: test
  application:
    name: springcloud-config-test
---
spring:
  profiles: cast
  application:
    name: NO ONE WILL GET SAFETY    